---
- name: Update CA Certificates
  shell: /usr/sbin/update-ca-certificates

- name: Add user www-data
  # This is the default user for nginx
  user:
    name: "{{ common_web_user }}"
    shell: /bin/false

# Determine if machine is provisioned via vagrant
# Some EC2-specific steps would need to be skipped
- name: check if instance is vagrant
  stat:
    path: /home/vagrant
  register: vagrant_home_dir

- name: add edx ppa apt key
  apt_key:
    id: "{{ COMMON_EDX_PPA_KEY_ID }}"
    keyserver: "{{ COMMON_EDX_PPA_KEY_SERVER }}"
    state: "present"

# Ensure that we get a current version of Git
# GitHub requires version 1.7.10 or later
# https://help.github.com/articles/https-cloning-errors
- name: Add git apt repository
  apt_repository:
    repo: "{{ common_git_ppa }}"

# We use this PPA to get the latest version of python 2.7
- name: Add edx apt repository
  apt_repository:
    repo: "{{ COMMON_EDX_PPA }}"

- name: Install role-independent useful system packages
  # do this before log dir setup; rsyslog package guarantees syslog user present
  apt:
    name: "{{ item }}"
    install_recommends: yes
    state: present 
    update_cache: yes
  with_items: common_debian_pkgs

- name: Create common directories
  file:
    path: "{{ item.path }}"
    state: "{{ item.state | default('directory') }}" 
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}" 
    mode: 0755
  with_items: common_directories

- name: upload sudo config for key forwarding as root
  copy:
    src: ssh_key_forward 
    dest: /etc/sudoers.d/ssh_key_forward
    validate: 'visudo -c -f %s' 
    owner: root 
    group: root 
    mode: 0440

- name: pip install virtualenv
  pip:
    name: "{{ item }}" 
    state: present
    extra_args: "-i {{ COMMON_PYPI_MIRROR_URL }}"
  with_items: common_pip_pkgs

- name: update /etc/hosts
  template: 
    src: hosts.j2 
    dest: /etc/hosts
  when: COMMON_HOSTNAME|length > 0
  register: etc_hosts

- name: update /etc/hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
  when: COMMON_HOSTNAME|length > 0
  register: etc_hostname

- name: run hostname
  shell: hostname -F /etc/hostname
  when: COMMON_HOSTNAME|length >0 and (etc_hosts.changed or etc_hostname.changed)

- name: Copy the templates to their respestive destination
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: root 
    group: root 
    mode: "{{ item.mode | default(644) }}"
  register: config_templates
  with_items:
    - { src: 'edx_rsyslog.j2', dest: '/etc/rsyslog.d/99-edx.conf' }
    - { src: 'etc/logrotate.d/hourly/edx_logrotate.j2', dest: '/etc/logrotate.d/hourly/edx-services' }
    - { src: 'etc/cron.hourly/logrotate.j2', dest: '/etc/cron.hourly/logrotate', mode: '555' }
    - { src: 'etc/logrotate.d/hourly/edx_logrotate_tracking_log.j2', dest: '/etc/logrotate.d/hourly/tracking.log' }

  # TODO: restarts no matter which template has changed, need to examine
  # the results
- name: restart rsyslogd
  service: name=rsyslog state=restarted
  sudo: True
  when: config_templates.changed
